[package]
name = "dsp-util"
version = "0.1.0"
authors = ["Dylan Ullrich <dylan@eldyl.org>"]
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
